### ISSUE TITLE
音乐播放页面的路由不应该是discover页面的子路由

### ISSUE THREAD

**Issue by Lancelotfan1991** [coderwhy/hy-react-web-music#4]
![image](https://user-images.githubusercontent.com/30165840/91650503-03156200-eab3-11ea-9741-df028af70580.png)
如上图。
音乐播放页面应该是一个跟discover平级的路由。因为从任何页面都有可能跳转至音乐播放页面。

看了网易云音乐的官网也是如此。music.163.com/#/song?id=111。

**Comment by coderwhy** [comment]
这个你可以自己定，我的路由规划并不是完全按照网易云的规划来的。
很多官网上的东西也不一定就是最佳实践，某些结构我喜欢自己来规划，而不完全是一致。

**Comment by Lancelotfan1991** [comment]
> 这个你可以自己定，我的路由规划并不是完全按照网易云的规划来的。
> 很多官网上的东西也不一定就是最佳实践，某些结构我喜欢自己来规划，而不完全是一致。

我知道了~thanks。

**Comment by coderPFY** [comment]
感谢王老师的讲解，受益匪浅


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "coderwhy/hy-react-web-music"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月31日(星期一) 下午3:13
收件人:&nbsp;"coderwhy/hy-react-web-music"<hy-react-web-music@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [coderwhy/hy-react-web-music] 音乐播放页面的路由不应该是discover页面的子路由 (#4)





 
Closed #4.
